"""Demo account for the public deployment.

`seed_demo` is idempotent and safe to run on every start: it (re)creates the
demo user, wipes whatever visitors changed in its tracker / briefs / tailored
resumes, makes sure the sample jobs exist, and restores the sample tracker
entries and pre-generated briefs. Sample data lives in app/demo/*.json:
real postings from the evaluation set (with their recorded LLM scores) and
briefs generated by the real pipeline.
"""

import json
import logging
import secrets
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path

from sqlalchemy import delete, select
from sqlalchemy.orm import Session

from app.core import security
from app.core.config import settings
from app.core.jobsources.base import job_fingerprint
from app.models.application import Application
from app.models.job import Job
from app.models.research_job import ResearchJob, ResearchSource
from app.models.tailored_resume import TailoredResume
from app.models.user import User
from app.repositories import user_repository

logger = logging.getLogger(__name__)

DEMO_DIR = Path(__file__).resolve().parents[1] / "demo"


class DemoDisabledError(Exception):
    pass


@dataclass
class SeedSummary:
    jobs_added: int = 0
    applications: int = 0
    briefs: int = 0


def _load(name: str) -> list[dict]:
    path = DEMO_DIR / name
    if not path.exists():
        logger.warning("Demo fixture %s not found; skipping", path)
        return []
    return json.loads(path.read_text(encoding="utf-8"))


def _parse_dt(value: str | None) -> datetime | None:
    if not value:
        return None
    parsed = datetime.fromisoformat(value)
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=UTC)


def get_or_create_demo_user(db: Session) -> User:
    user = user_repository.get_user_by_email(db, settings.demo_email)
    if user is None:
        # Random, never-shown password: the account is only reachable through POST /auth/demo.
        user = User(
            email=settings.demo_email, hashed_password=security.hash_password(secrets.token_urlsafe(32))
        )
        db.add(user)
        db.commit()
        db.refresh(user)
    return user


def _ensure_jobs(db: Session, now: datetime) -> tuple[dict[str, Job], int]:
    by_fingerprint: dict[str, Job] = {}
    added = 0
    for item in _load("jobs.json"):
        fingerprint = job_fingerprint(item["company"], item["title"])
        job = db.scalar(select(Job).where(Job.fingerprint == fingerprint))
        if job is None:
            job = Job(
                fingerprint=fingerprint,
                source=item["source"],
                external_id=item["external_id"],
                official_source=item["official_source"],
                title=item["title"],
                company=item["company"],
                location=item["location"],
                is_remote=item["is_remote"],
                url=item["url"],
                description=item["description"],
                tags=item["tags"],
                posted_at=_parse_dt(item.get("posted_at")),
                first_seen_at=now,
                last_seen_at=now,
                passed_prefilter=item["passed_prefilter"],
                prefilter_reason=item["prefilter_reason"],
                rule_score=item["rule_score"],
                red_flags=item.get("red_flags", []),
                llm_score=item.get("llm_score"),
                llm_reason=item.get("llm_reason"),
                fresher_friendly=item.get("fresher_friendly"),
                scored_at=now if item.get("llm_score") is not None else None,
                # Sample jobs must never go out in a real digest.
                digested_at=now,
            )
            db.add(job)
            added += 1
        by_fingerprint[fingerprint] = job
    db.flush()
    return by_fingerprint, added


def seed_demo(db: Session, now: datetime | None = None) -> SeedSummary:
    if not settings.demo_enabled:
        raise DemoDisabledError("DEMO_ENABLED is off")
    now = now or datetime.now(UTC)
    user = get_or_create_demo_user(db)
    summary = SeedSummary()

    # Reset everything a visitor could have changed.
    db.execute(delete(Application).where(Application.owner_id == user.id))
    db.execute(delete(TailoredResume).where(TailoredResume.owner_id == user.id))
    for brief in db.scalars(select(ResearchJob).where(ResearchJob.owner_id == user.id)):
        db.delete(brief)
    db.flush()

    jobs, summary.jobs_added = _ensure_jobs(db, now)

    today = now.date()
    for item in _load("applications.json"):
        job = jobs.get(job_fingerprint(item["company"], item["title"]))
        if job is None:
            continue
        applied = item.get("applied_days_ago")
        follow_up = item.get("follow_up_in_days")
        db.add(
            Application(
                owner_id=user.id,
                job_id=job.id,
                title=job.title,
                company=job.company,
                url=job.url,
                location=job.location,
                status=item["status"],
                notes=item.get("notes", ""),
                applied_on=today - timedelta(days=applied) if applied is not None else None,
                follow_up_on=today + timedelta(days=follow_up) if follow_up is not None else None,
            )
        )
        summary.applications += 1

    for item in _load("briefs.json"):
        # Keep the original generation time: seeded briefs must not count
        # against the daily LLM budget, and the UI should show when they were made.
        created = _parse_dt(item["generated_at"]) or now
        brief = ResearchJob(
            company=item["company"],
            owner_id=user.id,
            status="done",
            research=item.get("research", ""),
            analysis=item.get("analysis", ""),
            report=item.get("report", ""),
            final_report=item["final_report"],
            created_at=created,
            updated_at=created,
        )
        brief.sources = [
            ResearchSource(index=s["index"], title=s["title"], url=s["url"], snippet=s.get("snippet", ""))
            for s in item.get("sources", [])
        ]
        db.add(brief)
        summary.briefs += 1

    db.commit()
    logger.info(
        "Demo seeded: %d sample jobs added, %d tracker entries, %d briefs",
        summary.jobs_added,
        summary.applications,
        summary.briefs,
    )
    return summary


def demo_user_for_login(db: Session) -> User:
    if not settings.demo_enabled:
        raise DemoDisabledError("DEMO_ENABLED is off")
    return get_or_create_demo_user(db)
