"""add applications table

Revision ID: 2699219bce88
Revises: cfdb82c20d3d
Create Date: 2026-10-03 20:53:51.222925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2699219bce88'
down_revision: Union[str, None] = 'cfdb82c20d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('applied_on', sa.Date(), nullable=True),
    sa.Column('follow_up_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='fk_applications_job_id_jobs', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_applications_owner_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'job_id', name='uq_applications_owner_job')
    )
    op.create_index(op.f('ix_applications_follow_up_on'), 'applications', ['follow_up_on'], unique=False)
    op.create_index(op.f('ix_applications_owner_id'), 'applications', ['owner_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_owner_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_follow_up_on'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
