"""add tailored_resumes table

Revision ID: c6179ef2dc74
Revises: 2699219bce88
Create Date: 2026-10-03 21:08:17.937211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6179ef2dc74'
down_revision: Union[str, None] = '2699219bce88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tailored_resumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('job_title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('keywords_matched', sa.JSON(), nullable=False),
    sa.Column('keywords_missing', sa.JSON(), nullable=False),
    sa.Column('used_llm', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='fk_tailored_resumes_job_id_jobs', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_tailored_resumes_owner_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tailored_resumes_job_id'), 'tailored_resumes', ['job_id'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_owner_id'), 'tailored_resumes', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tailored_resumes_owner_id'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_job_id'), table_name='tailored_resumes')
    op.drop_table('tailored_resumes')
    # ### end Alembic commands ###
