"""add research_jobs.export_object_key

Revision ID: cae1e7198865
Revises: ec4aac329313
Create Date: 2026-10-02 11:34:25.716104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae1e7198865'
down_revision: Union[str, None] = 'ec4aac329313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_jobs', sa.Column('export_object_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_jobs', 'export_object_key')
    # ### end Alembic commands ###
