"""add job scoring and digest columns

Revision ID: cfdb82c20d3d
Revises: 1066196ecfcd
Create Date: 2026-10-03 20:31:58.799653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdb82c20d3d'
down_revision: Union[str, None] = '1066196ecfcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('llm_score', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('llm_reason', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('fresher_friendly', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('digested_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_jobs_llm_score'), 'jobs', ['llm_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_llm_score'), table_name='jobs')
    op.drop_column('jobs', 'digested_at')
    op.drop_column('jobs', 'scored_at')
    op.drop_column('jobs', 'fresher_friendly')
    op.drop_column('jobs', 'llm_reason')
    op.drop_column('jobs', 'llm_score')
    # ### end Alembic commands ###
